### ISSUE TITLE
High fidelity mockups for bulletins

### ISSUE THREAD

**Issue by achan** [openmcac/mcac-js#30]
Let's try to get some detailed designs for these two screens:

![bulletins-show-desktop](https://cloud.githubusercontent.com/assets/549222/6547414/ab0200c6-c5ad-11e4-9395-f6283126461e.png)

![bulletins-show-mobile](https://cloud.githubusercontent.com/assets/549222/5829151/b0df3a50-a0db-11e4-9360-d8339237e921.png)

Things to consider:

 - What should be our color scheme? My initial proposal would be purple and white... similar to [Yahoo](http://yahoo.com)... but I'm open for other ideas. The direction I want to go is have a minimalistic design with a white background. The highlight color can be whatever you want... but let's have a couple of options that the team can choose from.
 - What fonts should we use? How many different fonts and font sizes do we need? I'd suggest doing some research on Google to figure out the right balance.
 - For desktop, keep your design within a [12 column, 960px grid](http://grids.herokuapp.com). For more information, take a look at http://960.gs, there are photoshop templates that can give you some grid overlays.

As for the timeline, take your time. This is a **big** task that will take a while... just try to give us updates and prepare a little screenshot of your progress for each status meeting.

cc: @atsiang @chohinlo 

If you have any questions, you can email me directly or add a comment to this issue.

**Comment by chohinlo** [comment]
Desktop Mockups

First iteration:
https://www.dropbox.com/s/n84uey05am6hp6z/first_mockup.png?dl=0

Second iteration:
https://www.dropbox.com/s/8it3h2ykpqpe294/second_mockup.png?dl=0

Designed with the 960 grid in mind with Amanda's graphic.
The 960 template will be fully used for the next iteration.
A quick meeting was held at church on Sunday and we've agreed for now that the second mockup has a more favorable layout.

Please feel free to comment.

**Comment by atsiang** [comment]
https://www.dropbox.com/s/cariw83kp4k8kcp/mcacmockup.JPG?dl=0

uhh I forgot to use the 960 grid though XP

**Comment by achan** [comment]
Here's an updated version of the bulletin so far:

Desktop:
![bulletins-desktop](https://cloud.githubusercontent.com/assets/549222/6681099/425f908e-cc37-11e4-8f4c-108d126942d2.png)

Mobile:
![bulletins-mobile](https://cloud.githubusercontent.com/assets/549222/6681119/69a55782-cc37-11e4-8731-74a0e43ef091.png)

@chohinlo @atsiang Please let me know if you've got any suggestions on how to improve this!
