### ISSUE TITLE
Find a Markdown editor to fill in service order with

### ISSUE THREAD

**Issue by achan** [openmcac/mcac-js#6]
The service order is expected to be in Markdown format.

We'll need to research some libraries that we can use that will render a Markdown editor in place of a textarea.

**Comment by jyolewis** [comment]
hmm would this work in the framework we are using? "http://daringfireball.net/projects/markdown/"
seems like it's[Markdown] a text to HTML application

**Comment by achan** [comment]
The application you're pointing to converts Markdown to HTML. While we do need that, we need to render it client-side so it needs to be written  in JavaScript like https://github.com/evilstreak/markdown-js as opposed to the one you pointed to which is written in Perl.

However, this issue is specifically talking about providing an editor to the Bulletin form like http://www.codingdrama.com/bootstrap-markdown/.

**Comment by achan** [comment]
Potential libraries:

 - http://lab.lepture.com/editor/
 - http://www.codingdrama.com/bootstrap-markdown/
 - http://epiceditor.com

After evaluating them all, I think we'll just go with bootstrap-markdown. It seems the most lightweight. Personally, I like the look of the Lepture Editor the most, but it's not packaging it's JavaScript with Bower so it would cause too much pain to make it compatible with our app.
