### ISSUE TITLE
[Edge case] Support users from regions that do not have Daylight Savings

### ISSUE THREAD

**Issue by achan** [openmcac/mcac-js#8]
We determine whether daylight savings is in effect depending on whether `moment().isDST() === true`, which depends on the client.

As a result, if the user is in a region that does not follow DST, we won't know that we need to apply DST.

Caused by #7.

**Comment by jyolewis** [comment]
I don't quite  understand why we would need to [apply/not apply] the DST for clients who are not in our timezone
isn't there a way for the app to run a "global time" so that it can avoid issues like these??

**Comment by achan** [comment]
Good point. Maybe we can store it in GMT and then display it in local time.

**Comment by jyolewis** [comment]
yeah, sounds like a plan
